Reenabled svnversion.h, server don't compile without it and make process don't build it automatically.
This is a temporary solution, until orignial author of svnversion.h fixes the make process so it works
out of the box without resorting to a first "cd include; make svnversion.h; cd .." manual precompile step.

Sample output of compilation without it:
**
In file included from metaserver.c:48:
../include/version.h:1:68: error: svnversion.h: No such file or directory
make[1]: *** [metaserver.o] Error 1
**